#
# SYS reset (input) signal.  The sys_reset_n signal should be
# obtained from the PCI Express interface if possible.  For
# slot based form factors, a system reset signal is usually
# present on the connector.  For cable based form factors, a
# system reset signal may not be available.  In this case, the
# system reset signal must be generated locally by some form of
# supervisory circuit.  You may change the IOSTANDARD and LOC
# to suit your requirements and VCCO voltage banking rules.
# Some 7 series devices do not have 3.3 V I/Os available.
# Therefore the appropriate level shift is required to operate
# with these devices that contain only 1.8 V banks.
#

# See the PCIe example design for this
# set_property BOARD_PART_PIN pcie_perstn_rst [get_ports pcie_perstn]
set_property PULLUP true [get_ports PCIE_RESET_N]
set_property IOSTANDARD LVCMOS18 [get_ports PCIE_RESET_N]
set_property PACKAGE_PIN L8 [get_ports PCIE_RESET_N]
set_false_path -from [get_ports PCIE_RESET_N]

#
# LED Status Indicators for Example Design.
# LED 0-2 should be all ON if link is up and functioning correctly
# LED 3 should be blinking if user application is receiving valid clock
#

set_property IOSTANDARD LVCMOS12 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS12 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS12 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS12 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS12 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS12 [get_ports {LED[7]}]

set_property PACKAGE_PIN AL11 [get_ports {LED[0]}]
set_property PACKAGE_PIN AL13 [get_ports {LED[1]}]
set_property PACKAGE_PIN AK13 [get_ports {LED[2]}]
set_property PACKAGE_PIN AE15 [get_ports {LED[3]}]
set_property PACKAGE_PIN AM8 [get_ports {LED[4]}]
set_property PACKAGE_PIN AM9 [get_ports {LED[5]}]
set_property PACKAGE_PIN AM10 [get_ports {LED[6]}]
set_property PACKAGE_PIN AM11 [get_ports {LED[7]}]

# Decrease the drive strenght to ensure that we can have high speed ports
# on the same banks
set_property DRIVE 8 [get_ports {LED[0]}]
set_property DRIVE 8 [get_ports {LED[1]}]
set_property DRIVE 8 [get_ports {LED[2]}]
set_property DRIVE 8 [get_ports {LED[3]}]
set_property DRIVE 8 [get_ports {LED[4]}]
set_property DRIVE 8 [get_ports {LED[5]}]
set_property DRIVE 8 [get_ports {LED[6]}]
set_property DRIVE 8 [get_ports {LED[7]}]

# This tells the optimizer not to worry about optimizing paths to the LEDs
set_false_path -to [get_ports -filter NAME=~LED*]

# ZCU106 PCIe board settings
# Their board definition file and their documentation are not consistent.....
# they flipped the pin number of RX[3] and RX[2]
# Does laneswizzling help>????
# https://teledynelecroy.com/doc/understanding-lane-reversal-and-polarity
# Something really weird is going on when I look at the final constraints
# file.
# You can export it with the tcl command
#     write_xdc test.xdc
# But RX[3] and RX[2] are not visible in that document.
set_property PACKAGE_PIN AJ2 [get_ports {PCI_EXP_RXP[3]}]
set_property PACKAGE_PIN AJ1 [get_ports {PCI_EXP_RXN[3]}]
set_property PACKAGE_PIN AH4 [get_ports {PCI_EXP_TXP[3]}]
set_property PACKAGE_PIN AH3 [get_ports {PCI_EXP_TXN[3]}]

set_property PACKAGE_PIN AG2 [get_ports {PCI_EXP_RXP[2]}]
set_property PACKAGE_PIN AG1 [get_ports {PCI_EXP_RXN[2]}]
set_property PACKAGE_PIN AG6 [get_ports {PCI_EXP_TXP[2]}]
set_property PACKAGE_PIN AG5 [get_ports {PCI_EXP_TXN[2]}]

set_property PACKAGE_PIN AF4 [get_ports {PCI_EXP_RXP[1]}]
set_property PACKAGE_PIN AF3 [get_ports {PCI_EXP_RXN[1]}]
set_property PACKAGE_PIN AE6 [get_ports {PCI_EXP_TXP[1]}]
set_property PACKAGE_PIN AE5 [get_ports {PCI_EXP_TXN[1]}]

set_property PACKAGE_PIN AE2 [get_ports {PCI_EXP_RXP[0]}]
set_property PACKAGE_PIN AE1 [get_ports {PCI_EXP_RXN[0]}]
set_property PACKAGE_PIN AD4 [get_ports {PCI_EXP_TXP[0]}]
set_property PACKAGE_PIN AD3 [get_ports {PCI_EXP_TXN[0]}]


set_property PACKAGE_PIN AB7 [get_ports sys_clk_n]
set_property PACKAGE_PIN AB8 [get_ports sys_clk_p]

create_clock -period 10.000 -name sys_clk [get_ports sys_clk_p]

set_property MARK_DEBUG false [get_nets {riffa/cfg_negotiated_width[0]}]
set_property MARK_DEBUG false [get_nets {riffa/cfg_negotiated_width[1]}]
set_property MARK_DEBUG false [get_nets {riffa/cfg_negotiated_width[2]}]
set_property MARK_DEBUG false [get_nets {riffa/CONFIG_LINK_RATE[0]}]
set_property MARK_DEBUG false [get_nets {riffa/CONFIG_LINK_RATE[1]}]

set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/cfg_current_speed[0]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/cfg_current_speed[1]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/cfg_max_payload[0]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/cfg_max_payload[1]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/cfg_negotiated_width[0]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/cfg_negotiated_width[1]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/cfg_negotiated_width[2]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[79]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[55]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[59]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[63]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[67]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[83]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[71]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[75]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[95]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[87]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[99]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[91]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[111]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[115]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[103]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[107]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[127]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[119]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[123]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[23]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[27]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[15]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[3]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[9]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[19]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[35]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[31]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[43]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[39]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[51]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[47]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[11]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[82]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[78]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[54]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[58]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[62]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[66]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[70]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[74]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[94]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[98]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[86]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[90]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[110]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[114]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[102]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[106]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[126]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[118]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[122]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[14]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[2]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[6]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[18]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[26]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[22]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[34]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[30]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[42]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[38]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[50]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[46]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[10]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[81]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[53]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[57]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[61]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[65]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[69]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[77]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[73]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[85]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[93]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[97]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[89]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[109]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[113]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[101]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[105]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[125]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[117]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[121]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[17]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[5]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[1]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[8]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[13]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[25]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[21]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[33]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[29]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[41]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[37]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[45]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[49]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[80]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[52]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[56]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[60]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[64]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[68]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[76]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[72]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[84]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[96]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[92]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[88]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[100]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[108]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[112]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[104]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[124]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[116]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[120]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[16]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[0]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[4]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[7]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[12]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[20]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[24]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[28]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[32]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[36]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[40]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[44]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_cq_tdata[48]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[31]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[39]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[23]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[9]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[3]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[19]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[11]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[15]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[35]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[27]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[55]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[51]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[43]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[47]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[71]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[67]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[59]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[63]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[87]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[83]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[75]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[79]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[91]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[95]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[99]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[103]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[107]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[111]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[115]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[119]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[123]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[127]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[38]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[2]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[6]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[18]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[22]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[10]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[14]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[34]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[26]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[30]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[54]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[50]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[42]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[46]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[70]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[66]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[58]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[62]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[86]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[82]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[74]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[78]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[90]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[94]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[98]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[102]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[106]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[110]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[114]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[118]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[122]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[126]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[37]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[1]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[5]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[8]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[17]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[21]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[13]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[33]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[25]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[29]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[41]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[53]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[49]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[45]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[57]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[69]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[65]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[61]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[73]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[85]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[81]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[77]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[89]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[93]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[97]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[101]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[105]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[109]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[113]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[117]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[121]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[125]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[28]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[24]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[7]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[12]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[0]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[4]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[16]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[20]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[32]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[36]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[48]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[40]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[52]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[44]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[56]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[68]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[64]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[60]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[72]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[84]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[80]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[76]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[88]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[92]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[96]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[100]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[104]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[108]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[112]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[116]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[120]}]
set_property MARK_DEBUG true [get_nets {PCIeGen3x4If128_i/m_axis_rc_tdata[124]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list PCIeGen3x4If128_i/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/PHY_CORECLK]]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {PCIeGen3x4If128_i/cfg_negotiated_width[0]} {PCIeGen3x4If128_i/cfg_negotiated_width[1]} {PCIeGen3x4If128_i/cfg_negotiated_width[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {PCIeGen3x4If128_i/cfg_max_payload[0]} {PCIeGen3x4If128_i/cfg_max_payload[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {PCIeGen3x4If128_i/cfg_current_speed[0]} {PCIeGen3x4If128_i/cfg_current_speed[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list PCIeGen3x4If128_i/inst/store_ltssm]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets chnl_rx_clk]
